### ISSUE TITLE
map并发读写问题

### ISSUE THREAD

**Issue by dalaoting** [bilibili/kratos#445]
服务调用服务太过频繁会导致Instances map读写并发导致服务异常退出
![image](https://user-images.githubusercontent.com/30154644/69948292-4fcf0b00-152a-11ea-8447-eed0410e8547.png)
触发位置：
github.com/bilibili/kratos/pkg/naming/opt.go:168
github.com/bilibili/kratos/pkg/naming/discovery/discovery.go:284
github.com/bilibili/kratos/pkg/net/rpc/warden/resolver/resolver.go:124
github.com/bilibili/kratos/pkg/net/rpc/warden/resolver/resolver.go:84

**Comment by dalaoting** [comment]
fatal error: concurrent map read and map write

goroutine 5234426 [running]:
runtime.throw(0xda6c82, 0x21)
	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc00159aaf0 sp=0xc00159aac0 pc=0x42f522
runtime.mapaccess1_faststr(0xc6f540, 0xc0034f8570, 0xd8eb4c, 0x6, 0xffffffffffffffff)
	/usr/local/go/src/runtime/map_faststr.go:21 +0x44f fp=0xc00159ab60 sp=0xc00159aaf0 pc=0x412b5f
github.com/bilibili/kratos/pkg/naming.ScheduleNode.func1.1(0xc0032f1d80, 0xc0034f8570, 0xc000e71194, 0xb)
	/Users/cwt/Developer/Go/src/palpal/vendor/github.com/bilibili/kratos/pkg/naming/opt.go:168 +0x1d4 fp=0xc00159ad68 sp=0xc00159ab60 pc=0x868b04
github.com/bilibili/kratos/pkg/naming/discovery.(*Resolve).Fetch(0xc0034f9ad0, 0xec17a0, 0xc000034088, 0x1, 0xc00026a801)
	/Users/cwt/Developer/Go/src/palpal/vendor/github.com/bilibili/kratos/pkg/naming/discovery/discovery.go:284 +0x2db fp=0xc00159ae70 sp=0xc00159ad68 pc=0xafb99b
github.com/bilibili/kratos/pkg/net/rpc/warden/resolver.(*Resolver).updateproc(0xc003b0d680)
	/Users/cwt/Developer/Go/src/palpal/vendor/github.com/bilibili/kratos/pkg/net/rpc/warden/resolver/resolver.go:124 +0x13b fp=0xc00159afd8 sp=0xc00159ae70 pc=0x86bb9b
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00159afe0 sp=0xc00159afd8 pc=0x45ef11
created by github.com/bilibili/kratos/pkg/net/rpc/warden/resolver.(*Builder).Build
	/Users/cwt/Developer/Go/src/palpal/vendor/github.com/bilibili/kratos/pkg/net/rpc/warden/resolver/resolver.go:84 +0x32a

**Comment by dalaoting** [comment]
修改后引发新问题，出现以下日志后，服务出现假死现象，无法调用
[2019/12/03 18:21:00.183] [INFO] [/Users/cwt/Developer/Go/src/palpal/vendor/github.com/bilibili/kratos/pkg/net/rpc/warden/resolver/resolver.go:161] resolver: finally get 1 instances
[2019/12/03 18:21:00.184] [INFO] [/Users/cwt/Developer/Go/src/palpal/vendor/github.com/bilibili/kratos/pkg/net/rpc/warden/resolver/resolver.go:161] resolver: finally get 1 instances
[2019/12/03 18:21:00.185] [INFO] [/Users/cwt/Developer/Go/src/palpal/vendor/github.com/bilibili/kratos/pkg/net/rpc/warden/resolver/resolver.go:161] resolver: finally get 1 instances
[2019/12/03 18:21:00.185] [INFO] [/Users/cwt/Developer/Go/src/palpal/vendor/github.com/bilibili/kratos/pkg/net/rpc/warden/resolver/resolver.go:161] resolver: finally get 1 instances
[2019/12/03 18:21:00.185] [INFO] [/Users/cwt/Developer/Go/src/palpal/vendor/github.com/bilibili/kratos/pkg/net/rpc/warden/resolver/resolver.go:161] resolver: finally get 1 instances
[2019/12/03 18:21:00.185] [INFO] [/Users/cwt/Developer/Go/src/palpal/vendor/github.com/bilibili/kratos/pkg/net/rpc/warden/resolver/resolver.go:161] resolver: finally get 1 instances
[2019/12/03 18:21:00.185] [INFO] [/Users/cwt/Developer/Go/src/palpal/vendor/github.com/bilibili/kratos/pkg/net/rpc/warden/resolver/resolver.go:161] resolver: finally get 1 instances
[2019/12/03 18:21:00.186] [INFO] [/Users/cwt/Developer/Go/src/palpal/vendor/github.com/bilibili/kratos/pkg/net/rpc/warden/resolver/resolver.go:161] resolver: finally get 1 instances
[2019/12/03 18:21:00.186] [INFO] [/Users/cwt/Developer/Go/src/palpal/vendor/github.com/bilibili/kratos/pkg/net/rpc/warden/resolver/resolver.go:161] resolver: finally get 1 instances
[2019/12/03 18:21:00.188] [INFO] [github.com/bilibili/kratos/pkg/net/rpc/warden/resolver/resolver.go:161] resolver: finally get 1 instances
[2019/12/03 18:21:00.200] [INFO] [github.com/bilibili/kratos/pkg/net/rpc/warden/resolver/resolver.go:161] resolver: finally get 1 instances
[2019/12/03 18:21:00.206] [INFO] [github.com/bilibili/kratos/pkg/net/rpc/warden/resolver/resolver.go:161] resolver: finally get 1 instances
......
......

**Comment by dalaoting** [comment]
按照案例修改完之后，会导致通过discovery.Build(appid)后，Fetch(ctx)的节点永远返回空

**Comment by dalaoting** [comment]
func (c *consumer) getInstances(appId string, ctx *blademaster.Context) (ins *naming.Instance) {
	sum := 0
	rsl := c.dis.Build(appId)

	for { // NOTE: 通过watch返回的event chan =>
		ch := rsl.Watch()
		if _, ok := <-ch; !ok {
			return
		}
		// NOTE: <= 实时fetch最新的instance实例
		ins, ok := rsl.Fetch(ctx)
		if !ok {
			if sum < 1000 {
				sum++
				time.Sleep(time.Millisecond * 2)
				continue
			} else {
				return nil
			}
		}
		// get local zone instances, otherwise get all zone instances.
		if in, ok := ins.Instances[c.conf.Zone]; ok {
			return c.getInstance(in)
		} else {
			var dInstances []*naming.Instance
			for _, in := range ins.Instances {
				dInstances = append(dInstances, in...)
			}
			return c.getInstance(dInstances)
		}
	}
}

**Comment by dalaoting** [comment]
"github.com/bilibili/kratos/pkg/log"
"github.com/bilibili/kratos/pkg/naming"
"github.com/bilibili/kratos/pkg/naming/discovery"
"github.com/bilibili/kratos/pkg/net/http/blademaster"
"github.com/bilibili/kratos/pkg/net/rpc/warden/resolver"

func (c *consumer) getInstances(appId string, ctx *blademaster.Context) (ins *naming.Instance) {
	sum := 0
	rsl := c.dis.Build(appId)

	for { // NOTE: 通过watch返回的event chan =>
		ch := rsl.Watch()
		if _, ok := <-ch; !ok {
			return
		}
		// NOTE: <= 实时fetch最新的instance实例
		ins, ok := rsl.Fetch(ctx)
		if !ok {
			if sum < 1000 {
				sum++
				time.Sleep(time.Millisecond * 2)
				continue
			} else {
				return nil
			}
		}
		// get local zone instances, otherwise get all zone instances.
		if in, ok := ins.Instances[c.conf.Zone]; ok {
			return c.getInstance(in)
		} else {
			var dInstances []*naming.Instance
			for _, in := range ins.Instances {
				dInstances = append(dInstances, in...)
			}
			return c.getInstance(dInstances)
		}
	}
}

**Comment by lintanghui** [comment]
@dalaoting  已经修复，之前的修改在没有设置filter opt的时候确实有问题

**Comment by dalaoting** [comment]
> @dalaoting 已经修复，之前的修改在没有设置filter opt的时候确实有问题
刚刚试了一下还是不行，会出现死循环

**Comment by dalaoting** [comment]
@lintanghui 刚刚试了一下还是不行，会出现死循环

**Comment by lintanghui** [comment]
哪个地方会出现死循环

**Comment by dalaoting** [comment]
@lintanghui 
这是你修改的代码
if ok {
		var appIns *naming.InstancesInfo
		appIns, ok = app.zoneIns.Load().(*naming.InstancesInfo)
		ins, ok = app.zoneIns.Load().(*naming.InstancesInfo)
		ins.LastTs = appIns.LastTs
		ins.Scheduler = appIns.Scheduler
		if r.opt.Filter != nil {
			ins.Instances = r.opt.Filter(ins.Instances)
		} else {
			//ins.Instances = make(map[string][]*naming.Instance)
			for zone, in := range appIns.Instances {
				ins.Instances[zone] = in
			}
		}
		if r.opt.Scheduler != nil {
			ins.Instances[r.opt.ClientZone] = r.opt.Scheduler(ins)
		}
		if r.opt.Subset != nil && r.opt.SubsetSize != 0 {
			for zone, inss := range ins.Instances {
				ins.Instances[zone] = r.opt.Subset(inss, r.opt.SubsetSize)
			}
		}
	}

进来时appIns load的时候是已经拿到节点，但是 r.opt.Filter == nil所以进入了else块，块中首先就是make了新的map ins直接覆盖了 ins.Instances的值，也导致了appIns.Instances也没空值，最终就是把已存在的ins丢弃了，后面全部都是返回了空节点，我是直接把make那行也注释掉，不知对其他流程是否有影响

**Comment by lintanghui** [comment]
```ins, ok = app.zoneIns.Load().(*naming.InstancesInfo)  ```
代码里并没有这一行不存在ins被覆盖。你拉下最新代码试试

**Comment by dalaoting** [comment]
刚刚拉了新代码，测试暂时没发现有问题了

**Comment by dalaoting** [comment]
@lintanghui 问题来了....
服务发现服务时候，调用r.opt.Scheduler(ins)时，clientZone默认变成了 zone01 ，我的zone配置的不是这个，导致又取不到节点了

**Comment by lintanghui** [comment]
client Zone 只会更新client所在的zone的调度信息，你配置的zone是啥 对应zone是否有服务

**Comment by dalaoting** [comment]
我的Zone 配置的值是hz001，拉到节点的时候也是hz001的，但是调用r.opt.Scheduler(ins)时，clientZone的值是zone01

**Comment by lintanghui** [comment]
clientZone的值只会修改zone01 的机房调度信息， 并不会修改hz001 的调度信息，你读hz001照样能读到
